spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-ygt-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-ygt-test
#保存为utf-8